--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KenCir/PMMPEconomyCore
build-by-default: true
branches:
- master
projects:
  PMMPEconomyCore:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0.1
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
      - src: KenCir/PMMPLibFormAPI/LibFormAPI
        version: ^1.0.0
...
