--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OutiServer/EconomyCore
build-by-default: true
branches:
- master
projects:
  EconomyCore:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.1.1
      - src: KenCir/PMMPLibFormAPI/LibFormAPI
        version: ^1.0.0
...
