name: EconomyCore
author: Ken_Cir
version: 1.0.0
api: 4.0.0
main: outiserver\economycore\EconomyCore
src-namespace-prefix: outiserver\economycore

permissions:
  economy.command:
    description: Economy Command Permission
    default: true
  economy.command.economy.money:
    description: Money SubCommand Permission
    default: true
  economy.command.economy.form:
    description: Form SubCommand Permission
    default: true
  economy.command.admin.addMoney:
    description: AddMoney SubCommand Permission
    default: op
  economy.command.admin.removeMoney:
    description: RemoveMoney SubCommand Permission
    default: op
  economy.command.admin.setMoney:
    description: setMoney SubCommand Permission
    default: op